### ISSUE TITLE
Results of using Names for electric-operator-mode [not an issue]

### ISSUE THREAD

**Issue by davidshepherd7** [Malabarba/names#17]
Hi,

in the README you asked for reports on how using Names went with other
peoples packages. I've recently started using it for [electric operator](https://github.com/davidshepherd7/electric-operator), here's how it went.

All my tests passed in the end.

The character count decreased by 300 out of ~11,000. But these aren't very
reliable numbers: I wasn't correctly namespacing many of my newer functions
before. Also I'm using more descriptive names for some functions now which is a nice benefit that I hadn't really thought of before.

Some issues that I ran into:

* `names-print` doesn't print out all the code when run with a large
  namespace, at least for me. Specifically for the [usage example](https://github.com/Malabarba/names/blob/master/UsageExample.org#usage-example) I get:

	    (progn (defvar example-has-courage nil) (defmacro example-with-courage (name &rest body) "Evaluate BODY, don't evaluate NAME." (declare (debug ...) (indent defun)) (progn (\` ...))) :autoload (defun example-fight (evil) "Fight EVIL!" (example-with-courage evil (-fight-internal))) (defun example--fight-internal nil "Called by `example-fight'" (when example-has-courage (let ... ...))))

  (with the same lack of line breaks). Maybe I need to set a variable?

* dash's threading macros didn't/don't provide debug information, so they
  don't work with names. I submitted a
  [pull-request](https://github.com/magnars/dash.el/pull/147) which fixes
  this for Names but there's some uncertainty over whether it will work
  correctly with edebug (maybe you could take a look if you have time?).

So overall, really good! Thanks a lot for making Names :)

**Comment by Malabarba** [comment]
Thanks for the feedback! 

In order to avoid that truncation when printing you need to set the `eval-expression-print-length/level` variables to nil (or to something large, like 300).
However, don't do that yet! Inspired by your issue, I'm adding a new `names-pprint` command. You can just invoke this command anywhere inside your namespace and it will present a pretty-printed expansion of the namespace.

As for the threading macros. They're complicated, unfortunately. But I'm implementing a workaround. [Here's an example of what it'll look like](https://github.com/Malabarba/names/blob/dev/TheNittyGritty.org#the-theading-macros---and---).
Let me know if that works for you!

**Comment by davidshepherd7** [comment]
Both of those fixes look great :) 

I don't the changes have propagated through to melpa yet, so I'll give them a try tomorrow.

**Comment by Malabarba** [comment]
Yes, I was waiting for the tests to pass. I've merged to master now, so it should be on melpa soon. Make sure to update your `Package-Requires` version

**Comment by davidshepherd7** [comment]
The :functionlike-macros option works nicely. :)

The pretty print command is very helpful too. It would be a bit better if it could preserve whitespace, but I guess that's impossible?

**Comment by Malabarba** [comment]
It's impossible without losing my sanity. :)
Thought maybe there could be a command that only expands the defun at point, instead of everything.
